version: '3.3'
services:

# Frontend
  webapp_frontend:
    image: "webapp_frontend"
    container_name: webapp_frontend
    restart: always
    ports:
     - "80:5000"

 # Backend
  webapp_backend:
    image: "webapp_backend"
    container_name: webapp_backend
    restart: always
    ports:
     - "9001:9001"   
